python -u main.py \
--gpus 0 \
-e best_model_path \
--model resnet18_1w1a \
--results_dir ./ \
--save result \
--data_path DATA_PATH \
--dataset imagenet \
--epoch 1000 \
--lr 0.1 \
-b 256 \
-bt 128 \
